/*
 * @Author: your name
 * @Date: 2019-12-21 09:36:33
 * @LastEditTime : 2019-12-25 11:31:00
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /v2ex/js/action/types.js
 */
'use strict';

export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  LOAD_V2EX_SUCCESS: 'LOAD_V2EX_SUCCESS',
  LOAD_V2EX_FAIL: 'LOAD_V2EX_FAIL',
  LOAD_HOT_TIPS_SUCCESS: 'LOAD_HOT_TIPS_SUCCESS',
  LOAD_HOT_TIPS_FAIL: 'LOAD_HOT_TIPS_FAIL',
  LOAD_NODE_SUCCESS: 'LOAD_NODE_SUCCESS',
  LOAD_NODE_FAIL: 'LOAD_NODE_FAIL',
  LOAD_NEW_SUCCESS: 'LOAD_NEW_SUCCESS',
  LOAD_NEW_FAIL: 'LOAD_NEW_FAIL',
  LOAD_ALL_NODE_SUCCESS: 'LOAD_ALL_NODE_SUCCESS',
  LOAD_ALL_NODE_FAIL: 'LOAD_ALL_NODE_FAIL',
  // github
  LOAD_GIUHUB_REPO_SUCCESS: 'LOAD_GIUHUB_REPO_SUCCESS',
  LOAD_GIUHUB_REPO_FAIL: 'LOAD_GIUHUB_REPO_FAIL',
};
